version: '3.3'
services:
  fastapi-be:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: "fastapi-be"
    ports:
      - "8080:80"
    volumes:
      - ntlkdata:/root/nltk_data

  vuejs-fe:
    build:
      context: ./web_demo
    container_name: "vuejs-fe"
    ports:
      - "8000:80"

volumes:
  ntlkdata:
#  jupyter:
#    build:
#      context: ./jupyter
#    container_name: "my-jupyter"
#    ports:
#      - "8888:8888"

